<div class="container hoverable white" style="position: relative; top:200px; right: 0; width: 400px; height: 450px;"> 

              <?php echo (isset($this->alert)? $this->alert : '');?>                
                    <form action="<?php echo BASE; ?>cadastro/cadastrar/" class="form-horizontal container" method="post" style="position: relative; top: 50px;">
                      <div class="form-group input-fild col s6">
                        <label for="name" class="col-sm-3 control-label">Nome:</label>
                        <div class="col-sm-8">
                          <!-- required faz com que os campos tem que ser preenchidos obrigatóriamente-->
                          <input required type="text" name="name" class="form-control validade" id="name" placeholder="" value="<?php echo $this->request->post('name') ?>">
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="email" class="col-sm-3 control-label">E-mail:</label>
                        <div class="col-sm-8">
                          <input required type="email" name="email" class="form-control" id="email" placeholder="" value="<?php echo $this->request->post('email') ?>">
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="username" class="col-sm-3 control-label">Usuário:</label>
                        <div class="col-sm-8">
                          <input required type="text" name="username" class="form-control" id="username" placeholder="" value="<?php echo $this->request->post('username') ?>">
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="password" class="col-sm-3 control-label">Senha:</label>
                        <div class="col-sm-8">
                          <input required type="password" name="password" class="form-control" id="password" placeholder="">
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-10">
                          <button type="submit" class="btn btn-success" style ="border-radius: 20px;">Cadastrar</button>
                          <a href="login" class="btn waves-effect waves-light right" type="submit" style ="border-radius: 20px;"> Voltar </a>
                        </div>                        
                      </div>                      
                    </form>
            </div>
</div>
    </div>
</div>
