            <div class="panel-body"> 
                 <?php echo (isset($this->alert) ? $this->alert : ''); ?>           
            <form action="<?php echo BASE; ?>recuperar/solicitar/" class="form-horizontal" method="post">
                  <div class="form-group">
                    <label for="email" class="col-sm-2 control-label">E-mail</label>
                    <div class="col-sm-10">
                      <input type="email" class="form-control" name="email" id="email" placeholder="seuemail@dominio.com">
                    </div>
                  </div>                  
                  <div class="form-group">                    
                  </div>
                  <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                      <button type="submit" class="btn btn-success">Enviar Link de Recuperação</button>
                      <!--<a href="login" class="btn waves-effect waves-light right" type="submit"> Voltar </a>-->
                    </div>
                  </div>
            </form>
            </div>
        </div>
    </div>
</div>
