            <div class="container hoverable white" style="position: relative; top:200px; right: 0; width: 400px; height: 200px;"> 
                 <?php echo (isset($this->alert) ? $this->alert : ''); ?>           
            <form action="<?php echo BASE; ?>recuperar/solicitar/" class="form-horizontal container" method="post" style="position: relative; top: 50px;">
                  <div class="form-group">
                    <label for="email" class="col-sm-2 control-label">E-mail</label>
                    <div class="col-sm-10">
                      <input type="email" class="form-control" name="email" id="email" placeholder="seuemail@dominio.com">
                    </div>
                  </div>                  
                  <div class="form-group">                    
                  </div>
                  <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10 center">
                      <button type="submit" class="btn btn-success" style="border-radius: 20px;">Enviar Link de Recuperação</button>
                      <!--<a href="login" class="btn waves-effect waves-light right" type="submit"> Voltar </a>-->
                    </div>
                  </div>
            </form>
            </div>
        </div>
    </div>
</div>
