</div>
	<!-- Mexer no footer abrir o materialize.css-->
	<br><br><br><br><br><br><br><br><br><br><br>
	<footer class="page-footer">          
	    <div class="footer-copyright">
	        <div class="container center">
	            © Transporte I. <?php echo date("Y"); ?> - Todos os direitos reservados
	            <!--<a class="grey-text text-lighten-4 right" href="#!">More Links</a>-->
	        </div>
	    </div>
	</footer>
		<!--<footer class="page-footer">
		<div class="container">
		    <div class="row">
		        <div class="col-md-4 col-md-offset-4 text-center">
		            Transporte I.A <?php echo date("Y"); ?> &copy; - Todos os direitos reservados
		        </div>
		    </div>
		</div>
		</footer>-->
	<!--<script type="<?php echo BOWER; ?>jquery/dist/jquery.min.js"></script>
	<script type="<?php echo BOWER; ?>bootstrap/dist/js/bootstrap.min.js"></script>-->
	<script type="text/javascript" src="jquery/dist/https://code.jquery.com/jquery-3.2.1.min.js"></script>
      <script type="text/javascript" src="public\bower_components\bootstrap\dist\js\materialize.min.js"></script>
	
      
     


</body>
</html> 