<!doctype html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="author" content="Cristian Renato">
        <meta name="generator" content="HXPHP Framework">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

        <link type="text/css" rel="stylesheet" href="public/css/materialize.css"  media="screen,projection"/>       
    
        <title><?php echo $view_title; ?></title>

        <style type="text/css">
            body{
                margin: 0 auto ;
                width:700px ;
                background: white;
                padding:50px ;
            }

            form{
                padding: 20px;
            }
        </style>
        <!-- bootstrap
        <link rel="shortcut icon" href="<?php// echo IMG; ?>favicon.jpg" type="image/x-icon">
        <link rel="stylesheet" href="<?php //echo BOWER; ?>bootstrap/dist/css/bootstrap.min.css" type="text/css">
        <link rel="stylesheet" href="<?php //echo BOWER; ?>font-awesome/css/font-awesome.min.css" type="text/css">
        <link rel="stylesheet" href="<?php //echo CSS; ?>main.css" type="text/css"> -->
        <?php
        echo $add_css;
        echo $add_js;
        ?>
    </head>
    <body class="amber accent-3">
        <div>

            <div class="container row hoverable white">
            <div class="col-md-6 col-md-offset-3">
                <div class="panel panel-custom">
                    <div class="panel-heading">
                        <!--<a id="logo" href="<?php //echo BASE; ?>">
                            <img class="img-responsive" src="<?php //echo IMG; ?>hxphp-logo.png" alt="">
                        </a>--> <br>
                        <div class="panel-body">
                            <?php echo (isset($this->alert) ? $this->alert : ''); ?>                      
                         </div>



                         